# FROM node:20-alpine

# COPY start.sh /usr/src

# RUN mkdir -p /usr/src/bot

# CMD /usr/src/start.sh

FROM node:20-alpine

# Set working directory to /app
WORKDIR /app

# Start the application
CMD ["npm", "start"]